"""empty message

Revision ID: 255e014e6c70
Revises: 5d4f83fbfee1
Create Date: 2021-06-14 22:33:58.068164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255e014e6c70'
down_revision = '5d4f83fbfee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
